// File generated by FlutterFire CLI & customized for Lucifax LightChat
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUTmhtOaJnmdr74D0K1GPMs4x_L121so',
    appId: '1:926525610962:web:24441e5ebad07f57b6860b',
    messagingSenderId: '926525610962',
    projectId: 'lucifax-lightchat',
    authDomain: 'lucifax-lightchat.firebaseapp.com',
    storageBucket: 'lucifax-lightchat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGUTmhtOaJnmdr74D0K1GPMs4x_L121so',
    appId: '1:926525610962:android:24441e5ebad07f57b6860b',
    messagingSenderId: '926525610962',
    projectId: 'lucifax-lightchat',
    storageBucket: 'lucifax-lightchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUTmhtOaJnmdr74D0K1GPMs4x_L121so',
    appId: '1:926525610962:ios:24441e5ebad07f57b6860b',
    messagingSenderId: '926525610962',
    projectId: 'lucifax-lightchat',
    storageBucket: 'lucifax-lightchat.firebasestorage.app',
    iosBundleId: 'com.Lucifax.LightChat',
  );
}
